### ISSUE TITLE
ImportError: no module named 'control'

### ISSUE THREAD

**Issue by nathanmlim** [Eigenstate/vmd-python#3]
Hi! Awesome work in making vmd python3 compatiable and conda installable!

Although, I am having trouble importing the module. Traceback below:

```
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/limn1/anaconda3/lib/python3.5/site-packages/GromacsWrapper-0.6.1-py3.5.egg/vmd/__init__.py", line 41, in <module>
ImportError: No module named 'control'
```

Suggestions?

**Comment by Eigenstate** [comment]
Hmmm, that is strange. It appears the error message isn't coming from my
vmd-python package, but instead from a GromacsWrapper package? I'm not
familiar with this code, but if you try removing it or even move that
directory somewhere else it may work.

Long-term, I may have a naming conflict with something the Gromacs people
release. Maybe they wrap vmd up or name something that. I'll look into that
further next week (am on vacation lol)

On Mar 20, 2017 6:33 PM, "Nathan Lim" <notifications@github.com> wrote:

Hi! Awesome work in making vmd python3 compatiable and conda installable!

Although, I am having trouble importing the module. Traceback below:

Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/limn1/anaconda3/lib/python3.5/site-packages/GromacsWrapper-0.6.1-py3.5.egg/vmd/__init__.py",
line 41, in <module>
ImportError: No module named 'control'

Suggestions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Eigenstate/vmd-python/issues/3>, or mute the thread

**Comment by Eigenstate** [comment]
Closing this due to inactivity. Please let me know if you still have problems!
