### ISSUE TITLE
TCL related error when installing using pip3.6

### ISSUE THREAD

**Issue by RasmusFonseca** [Eigenstate/vmd-python#8]
```bash
DN525uqm:~/Programs $ pip3.6 install -i https://pypi.anaconda.org/rbetz/simple vmd-python
Collecting vmd-python
  Downloading https://pypi.anaconda.org/rbetz/simple/vmd-python/2.0.4/vmd-python-2.0.4.tar.gz (27.8MB)
    100% |████████████████████████████████| 27.8MB 71kB/s
Building wheels for collected packages: vmd-python
  Running setup.py bdist_wheel for vmd-python ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/tmp9f0_asgbpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Compiling VMD
  Finding libraries...
  WARNING: Could not find library file 'libtcl8.5.dylib' in standard library directories.
   Defaulting to: '/usr/local/opt/python3/3.6/lib/libtcl8.5.dylib'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 273, in <module>
      'test': VMDTest,
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 31, in run
      self.execute(self.compile, [], msg="Compiling VMD")
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 44, in compile
      self.set_environment_variables(pydir)
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 163, in set_environment_variables
      os.environ["TCL_LIBRARY_DIR"] = self._find_library_dir("libtcl8.5", pydir)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 674, in __setitem__
      value = self.encodevalue(value)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 742, in encode
      raise TypeError("str expected, not %s" % type(value).__name__)
  TypeError: str expected, not NoneType

  ----------------------------------------
  Failed building wheel for vmd-python
  Running setup.py clean for vmd-python
Failed to build vmd-python
Installing collected packages: vmd-python
  Running setup.py install for vmd-python ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-c2w5byfo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Compiling VMD
    Finding libraries...
    WARNING: Could not find library file 'libtcl8.5.dylib' in standard library directories.
     Defaulting to: '/usr/local/opt/python3/3.6/lib/libtcl8.5.dylib'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 273, in <module>
        'test': VMDTest,
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 31, in run
        self.execute(self.compile, [], msg="Compiling VMD")
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
        func(*args)
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 44, in compile
        self.set_environment_variables(pydir)
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py", line 163, in set_environment_variables
        os.environ["TCL_LIBRARY_DIR"] = self._find_library_dir("libtcl8.5", pydir)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 674, in __setitem__
        value = self.encodevalue(value)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 742, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not NoneType

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-c2w5byfo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-fboeyl5o/vmd-python/
```

**Comment by Eigenstate** [comment]
I don't have access to an OSX machine so it may be a little annoying to debug this but I think I know how to fix things if I have some more info.

Is /usr/local/opt/python3/3.6/lib/libtcl8.5.dylib a file? Is it somewhere else, maybe /usr/lib?
Is it libtcl8.6.dylib instead?

**Comment by RasmusFonseca** [comment]
Ah yeah that'd be annoying. Ill be happy to come by in person. To answer your question:

```bash
$ find /usr/lib -name "libtcl*"
/usr/lib/libtcl.dylib
/usr/lib/libtcl8.5.dylib
/usr/lib/libtclstub8.5.a
```

**Comment by RasmusFonseca** [comment]
Theres also 
```
/usr/local/Cellar/tcl-tk/8.6.4/lib/libtcl8.6.dylib
/usr/local/Cellar/tcl-tk/8.6.4/lib/libtclstub8.6.a
/usr/local/Cellar/tcl-tk/8.6.7/lib/libtcl8.6.dylib
/usr/local/Cellar/tcl-tk/8.6.7/lib/libtclstub8.6.a
```

**Comment by Eigenstate** [comment]
I'm actually out of town... but we can still figure it out.
is $DYLD_LIBRARY_PATH set to anything?

**Comment by RasmusFonseca** [comment]
Nothing that points to subdirs of `/usr` (just intel compiler stuff). 
```bash
$ echo $DYLD_LIBRARY_PATH | tr ':' '\n'
/opt/intel//compilers_and_libraries_2016.2.146/mac/compiler/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/compiler/lib/intel64
/opt/intel//compilers_and_libraries_2016.2.146/mac/ipp/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/compiler/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/mkl/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/tbb/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/daal/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/daal/../tbb/lib
/opt/intel//compilers_and_libraries_2016.2.146/mac/daal/../compiler/lib
```

**Comment by Eigenstate** [comment]
Try cloning this repo and building again. I think b7ec401 should fix it-- the installer wasn't looking in all the relevant places for the library.

**Comment by RasmusFonseca** [comment]
Would this relate to a pip install? I'm not sure how to point pip to  a particular commit.

**Comment by Eigenstate** [comment]
Oh, I meant this repo.
```
git clone https://github.com/Eigenstate/vmd-python.git
cd vmd-python
python setup.py install
```
I also updated the anaconda installer so pip install should have that commit. The version string should be 2.0.5.

**Comment by RasmusFonseca** [comment]
Hm. I'm getting roughly the same error:

```bash
DN525uqm:~/Programs/vmd-python $ python3.6 setup.py install
/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
running install
running build
Compiling VMD
Finding libraries...
Traceback (most recent call last):
  File "setup.py", line 293, in <module>
    'test': VMDTest,
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 30, in run
    self.execute(self.compile, [], msg="Compiling VMD")
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 335, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/util.py", line 301, in execute
    func(*args)
  File "setup.py", line 43, in compile
    self.set_environment_variables(pydir)
  File "setup.py", line 183, in set_environment_variables
    fallback=False)
  File "setup.py", line 141, in _find_library_dir
    + os.environ.get("DYLD_FALLBACK_LIBRARY_PATH").split(":")
AttributeError: 'NoneType' object has no attribute 'split'
DN525uqm:~/Programs/vmd-python $ pip install -i https://pypi.anaconda.org/rbetz/simple vmd-python
Collecting vmd-python
  Downloading https://pypi.anaconda.org/rbetz/simple/vmd-python/2.0.5/vmd-python-2.0.5.tar.gz (27.8MB)
    100% |████████████████████████████████| 27.8MB 67kB/s
Building wheels for collected packages: vmd-python
  Running setup.py bdist_wheel for vmd-python ... error
  Complete output from command /Users/rfonseca/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/tmppgyyv9r0pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Compiling VMD
  Finding libraries...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 293, in <module>
      'test': VMDTest,
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/rfonseca/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 30, in run
      self.execute(self.compile, [], msg="Compiling VMD")
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 43, in compile
      self.set_environment_variables(pydir)
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 183, in set_environment_variables
      fallback=False)
    File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 141, in _find_library_dir
      + os.environ.get("DYLD_FALLBACK_LIBRARY_PATH").split(":")
  AttributeError: 'NoneType' object has no attribute 'split'

  ----------------------------------------
  Failed building wheel for vmd-python
  Running setup.py clean for vmd-python
Failed to build vmd-python
Installing collected packages: vmd-python
  Running setup.py install for vmd-python ... error
    Complete output from command /Users/rfonseca/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-_1r3mvr5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Compiling VMD
    Finding libraries...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 293, in <module>
        'test': VMDTest,
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/rfonseca/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 30, in run
        self.execute(self.compile, [], msg="Compiling VMD")
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/util.py", line 301, in execute
        func(*args)
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 43, in compile
        self.set_environment_variables(pydir)
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 183, in set_environment_variables
        fallback=False)
      File "/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py", line 141, in _find_library_dir
        + os.environ.get("DYLD_FALLBACK_LIBRARY_PATH").split(":")
    AttributeError: 'NoneType' object has no attribute 'split'

    ----------------------------------------
Command "/Users/rfonseca/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-_1r3mvr5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/pm/vtj2fdz94xxfw2sr59lsyrw40000gn/T/pip-build-t6gu3o10/vmd-python/
```

**Comment by Eigenstate** [comment]
Oops, I had a dumb mistake in there. Git pull and try again? It'll still be 2.0.5

**Comment by RasmusFonseca** [comment]
Some progress .. new error 😀 

```
DN525uqm:~/Programs/vmd-python $ git pull
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/Eigenstate/vmd-python
   359ef40..df505fc  master     -> origin/master
Updating 359ef40..df505fc
Fast-forward
 setup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
DN525uqm:~/Programs/vmd-python $ python3.6 setup.py install
/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
running install
running build
Compiling VMD
Finding libraries...
Traceback (most recent call last):
  File "setup.py", line 293, in <module>
    'test': VMDTest,
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 30, in run
    self.execute(self.compile, [], msg="Compiling VMD")
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/cmd.py", line 335, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/Users/rfonseca/anaconda3/lib/python3.6/distutils/util.py", line 301, in execute
    func(*args)
  File "setup.py", line 43, in compile
    self.set_environment_variables(pydir)
  File "setup.py", line 183, in set_environment_variables
    fallback=False)
  File "/Users/rfonseca/anaconda3/lib/python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/Users/rfonseca/anaconda3/lib/python3.6/os.py", line 744, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```

**Comment by Eigenstate** [comment]
Hmmm that means it's still not finding libtcl in the right spot. Try it again?
```
git pull
python setup.py build
python setup.py install
```

**Comment by RasmusFonseca** [comment]
Finally back. It works now! 

For the record, my python installation is through anaconda3 and I had to run `brew install netcdf` first. 

Thank you
